### ISSUE TITLE
Sidebar with IE11

### ISSUE THREAD

**Issue by arjarn** [olton/Metro4-M4Q#2]
If I cut and paste SideBar example in Metro 4 Sandbox (with CDN for using Metro4-M4Q), I have an error with IE11 (all ok with chrome, edge and firefox).

Error is metro.js : line1234 bad action with object 

Line 1234 is  e = new CustomEvent(name, data || {});

Thanx for your help.

**Comment by olton** [comment]
fixed, wait ~30min for CDN is updated
