### ISSUE TITLE
Feature request: Method to bring a window to top

### ISSUE THREAD

**Issue by shajeeck** [olton/Metro4-M4Q#3]
It will be nice to have a  method to bring window on top of all other windows like close(), hide()
Same function as if when clicking on the window-caption. 

Also it is a common design to bring the window to top when clicking any where on  the window. Now only window-caption brings the window to top

**Comment by olton** [comment]
This logic you must create own :).

**Comment by shajeeck** [comment]
I tried searching your code to see the logic how u bring window to top when window-caption is clicked. I understood that u change the order of  window divs but, couldn't find m4q code. If you can point me i can submit a PR

**Comment by olton** [comment]
https://github.com/olton/Metro4-M4Q/tree/master/docs/examples/desktop
