### ISSUE TITLE
Updated version ?

### ISSUE THREAD

**Issue by arjarn** [olton/Metro4-M4Q#5]
I'm using Metro4-M4Q for my development with last build of m4q (and Vegas plugin :) )

Your upgrades of Metro-UI-CSS are great (and 4.2.41 with firing event promizing lot of fun).

How about versioning of Metro4-M4Q ?

Thanx for your impressive work.

**Comment by olton** [comment]
After adding triggers in 4.2.41, I will merge changes from 4.2.40 and 4.2.41 into metro4-m4q. Unfortunately, I have only 2 hands and one head :(

**Comment by arjarn** [comment]
Thanx, I understand how it may be hard to maintain 2 versions. Need time.

**Comment by olton** [comment]
https://github.com/olton/Metro-UI-CSS/blob/4.2.43/CHANGELOG.md

Utils: add methods isM4Q, isQ. Method isQ return one of isJQuery or isM4Q ;)

**Comment by olton** [comment]
https://github.com/olton/Metro-UI-CSS/tree/4.3.0
